### ISSUE TITLE
Rename the repo/package/module?

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/configyaml#17]
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

So the package should really be `configloader`? Maybe just do the same for module and repo too?

**Comment by davegaeddert** [comment]
This possibility just occurred to me: https://pypi.python.org/pypi/configloader/1.0.1

Ideas?

**Comment by davegaeddert** [comment]
`configfile`?

**Comment by paulortman** [comment]
configyaml is chosen

**Comment by paulortman** [comment]
closed by #20
