### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/configyaml#3]
Turns out it would be very helpful to have a semi-proper release process. When version numbers don't get bumped then installing specific commits doesn't really work how I expected.

Minimum:
- bump version (look at cookiecutter project, I removed that part)

Better:
- create tags
- GitHub release and changelog based on commits...

Best:
- publish to pypi...

**Comment by paulortman** [comment]
I think perhaps the [zest.release](http://zestreleaser.readthedocs.io/en/latest/index.html) tool would be a nice way to do releases.

**Comment by davegaeddert** [comment]
Sounds good to me.

**Comment by davegaeddert** [comment]
Let me know if you need anything for pypi, I'd like to set up a shared "dropseed" account if that's how it works.

**Comment by paulortman** [comment]
Looks like we've got a fairly complete process using the zest.releaser script/tool.

 - The package on [pypi](https://pypi.python.org/pypi/configyaml/)
 - The tag/release on [GitHub](https://github.com/dropseedlabs/configyaml/releases)
