### ISSUE TITLE
Re-cookiecutter

### ISSUE THREAD

**Issue by davegaeddert** [dropseedlabs/configyaml#5]
I generated this using https://github.com/audreyr/cookiecutter-pypackage, which I had mixed feelings about doing. I stripped a lot of stuff out too -- docs, bumpversion/release stuff, even looks like they have a basic cli setup. Given that those are all things I think we probably want now, it might be worth just re-running the cookiecutter process and dropping our handful of files back in... We definitely need a real release process, might as well push it to pypi and install from there, and then I think it probably makes sense to just write some basic docs too, since we'll probably do it anyway (and should). Don't think all of that stuff is worth reinventing.

**Comment by paulortman** [comment]
closed by #15
